web/router.ex
defmodule PandaUi.Router do
  use PandaUi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PandaUi do
    pipe_through :browser # Use the default browser stack

    #get "/", PageController, :index
    get "/", MatchController, :index
    get "/matches/:id", MatchController, :show
    
  end

  # Other scopes may use custom stacks.
  # scope "/api", PandaUi do
  #   pipe_through :api
  # end
end

lib/panda_ui/cache.ex
defmodule PandaUi.Cache do
  use Nebulex.Cache, otp_app: :panda_ui
end

lib/panda_ui/endpoint.ex
defmodule PandaUi.Endpoint do
  use Phoenix.Endpoint, otp_app: :panda_ui

  socket "/socket", PandaUi.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :panda_ui, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_panda_ui_key",
    signing_salt: "CHpQHeoB"

  plug PandaUi.Router
end

web/models/match.ex
defmodule PandaUi.Match do
    
    use PandaUi.Web, :model

    def upcoming_matches do
        url = "https://api.pandascore.co/matches/upcoming?sort=begin_at&page[size]=5&token=" <> System.get_env("token")
        %{body: body} = HTTPoison.get!(url, [], [ ssl: [{:versions, [:'tlsv1.2']}] ])
        r = Poison.Parser.parse! body
        for n <- r, do: %{"begin_at" => n["begin_at"], "id" => n["id"], "name" => n["name"]}
    end

    def odds_for_match(match_id) do
        url = "https://api.pandascore.co/matches/" <> Integer.to_string(match_id) <> "?&token=" <> System.get_env("token")
        %{body: body} = HTTPoison.get!(url, [], [ ssl: [{:versions, [:'tlsv1.2']}] ])
        r = Poison.Parser.parse! body

        #Number of matches opponent1 won
        opp1_won_matches_url = "https://api.pandascore.co/matches/?filter[winner_id]=" <> Integer.to_string(List.first(r["opponents"])["id"]) 
          <> "&token=" <> System.get_env("token")
        %{body: body} = HTTPoison.get!(opp1_won_matches_url, [], [ ssl: [{:versions, [:'tlsv1.2']}] ])
        opp1_won_matches = length(Poison.Parser.parse! body)

        #Number of matches opponent2 won
        opp2_won_matches_url = "https://api.pandascore.co/matches/?filter[winner_id]=" <> Integer.to_string(List.last(r["opponents"])["id"]) 
          <> "&token=" <> System.get_env("token")
        %{body: body} = HTTPoison.get!(opp2_won_matches_url, [], [ ssl: [{:versions, [:'tlsv1.2']}] ])
        opp2_won_matches = length(Poison.Parser.parse! body)

        #Calculate odds based on the number of matches each opponent won before
        ratio = if (opp1_won_matches == 0 || opp2_won_matches == 0), do: :rand.uniform, else: opp1_won_matches / opp2_won_matches
        opp2_odds = 100 / (ratio + 1)
        opp1_odds = 100 - opp2_odds

        %{List.first(r["opponents"])["opponent"]["name"] => opp1_odds, List.last(r["opponents"])["opponent"]["name"] => opp2_odds}
    end
    
    def odds_using_cache(match_id) do
        if PandaUi.Cache.has_key?(match_id) do
            #IO.puts "It's available in the cache"
            PandaUi.Cache.get(match_id)
        else
            result = odds_for_match(match_id)
            #IO.inspect result
            #"The result is stored in the cache for future requests"
            PandaUi.Cache.set(match_id, result)
        end
    end 
    
end

web/controllers/match_controller.ex
defmodule PandaUi.MatchController do
  use PandaUi.Web, :controller
  
  alias PandaUi.Match

  def index(conn, _params) do
    matches = Match.upcoming_matches
    render conn, "index.html", matches: matches
  end
  
  def show(conn, %{"id" => match_id}) do
    render conn, "show.html", match_id: match_id
  end
end

web/controllers/page_controller.ex
defmodule PandaUi.PageController do
  use PandaUi.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/error_view.ex
defmodule PandaUi.ErrorView do
  use PandaUi.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule PandaUi.LayoutView do
  use PandaUi.Web, :view
end

web/views/match_view.ex
defmodule PandaUi.MatchView do
  use PandaUi.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PandaUi!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/match/index.html.eex
<h1>Welcome!</h1>
<h3>5 upcoming matches are:</h3>

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Begin at</th>
            <th>Name</th>
            <th>Odds</th>
        </tr>
    </thead>
    
    <tbody>
        <%= for match <- @matches do %>
            <tr>
                <td><%= match["id"] %></td>
                <td><%= match["begin_at"] %></td>
                <td><%= link match["name"], to: match_path(@conn, :show, match["id"]) %></td>
                <td></td>
            </tr>
        <% end %>
    </tbody>
</table>

web/templates/match/show.html.eex
<div class="loading"></div>
<h1>Odds for match: <%= @match_id %></h1>


<ul class="match-odds">
</ul>

<script>
    document.addEventListener("DOMContentLoaded", function(){
        window.createSocket(<%= @match_id %>)    
        $(".loading").fadeOut("slow")
    });
</script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>